### ISSUE TITLE
Shift Click not working

### ISSUE THREAD

**Issue by Hellcode48** [MinusKube/SmartInvs#32] opened 2018-10-26 06:17 UTC
when I use: e.getClick() == ClickType.SHIFT_LEFT nothing happens..

**Comment by MinusKube** [comment] 2018-10-28 17:42
Oh yeah, that's due to this line https://github.com/MinusKube/SmartInvs/blob/6d0a1d8e0f6773f9317d48db1108e414f50732de/src/main/java/fr/minuskube/inv/InventoryManager.java#L115

I'll fix that as soon as possible :)

**Comment by MinusKube** [comment] 2018-10-28 19:51
Mhhh, I'm testing, but the problem is that it seems like Spigot provides no way to detect "Double Shift Click" on an item, and, double shift clicking on an item executes the action of every item similar to the clicked one.

**Comment by Ytnoos** [comment] 2019-06-14 12:15
I don't know where the problem is. InventoryClickEvent calls shift clicks, with different ClickType
https://prnt.sc/o1tfnu

**Comment by TheTechmo** [comment] 2019-11-03 04:57
Can this be fixed at all?

**Comment by MinusKube** [comment] 2021-06-04 15:43
Fixed by #186, but the problem I mentioned earlier still subsists, we'll have to either find a workaround, or warn the users about it.

**Closed by MinusKube** 2021-06-04 15:43 UTC
Labels: bug
