### ISSUE TITLE
[Modded] MouseTweaks: Space-Clicking Shortcut takes the whole inventory as if it was a chest

### ISSUE THREAD

**Issue by TheFlash787** [MinusKube/SmartInvs#40] opened 2019-01-02 00:21 UTC
Hey! So many modpacks have a mod called MouseTweaks which allows you to use shortcuts to transfer items around inventories.

In this mod, you can hold space and click to transfer a whole inventory into another inventory (e.g. A chest into an inventory). In 1.12 Sponge, the clickable GUIs you make are not affected by this and 'space clicking' doesn't take the inventory.

However in Spigot/Bukkit/Thermos (Using 1.7.10), when I 'space click' the inventory, all of the items are moved from the GUI into the inventory and are still there after closing. I have even tested relogging or dying and the items still persist.

Thank you!
Ally.

**Comment by MinusKube** [comment] 2019-08-25 02:49
Hi, I couldn't reproduce the issue, firstly the MouseTweaks mod doesn't seem to have a Space + Click feature, so, I tried with the InventoryTweaks mod (which has this feature), and everything worked perfectly.

I tried with Spigot 1.7.10.

Maybe the issue has already been unintentionally fixed. If someone is able to reproduce the issue, I would love to have some more information.

**Comment by MinusKube** [comment] 2021-06-04 16:00
I'm closing this as I am unable to reproduce the issue, we had no updates in 2 years, and the way we handle inventory clicks has changed a lot since then. Feel free to comment the issue if anyone has any news on this, and I'll reopen it.

**Closed by MinusKube** 2021-06-04 16:00 UTC
Labels: bug
