### ISSUE TITLE
Click Listeners not invoked when Slot is empty

### ISSUE THREAD

**Issue by GitGraf** [MinusKube/SmartInvs#79] opened 2019-11-21 23:14 UTC
When I add a click listener via the `Builder#listener()` method, the consumer is not invoked if the clicked slot and the cursor is empty.

Example:
```java
SmartInventory inv = SmartInventory.builder()
    .manager(myManager)
    .provider(new MyInvProvider())
    .listener(new InventoryListener<InventoryClickEvent>(InventoryClickEvent.class, e -> {
        e.getWhoClicked().sendMessage("Slot: " + e.getSlot());
    }))
    .build();

// Provider
class MyInvProvider implements InventoryProvider {
    @Override
    public void init(Player player, InventoryContents contents) {
        contents.fillRow(1, ClickableItem.empty(new ItemStack(Material.DIRT)));
    }
    @Override
    public void update(Player player, InventoryContents contents) {}
}
```
The clicked slot is only displayed when clicking on one of the dirt blocks in the inventory.

**Comment by Oscaz** [comment] 2020-01-03 09:49
This caused by the check for InventoryAction.NOTHING in InventoryManager,

```java
if (e.getAction() == InventoryAction.NOTHING && e.getClick() != ClickType.MIDDLE) {
    e.setCancelled(true);
    return;
}
```

**Comment by MinusKube** [comment] 2021-06-04 16:17
Fixed by #186

**Closed by MinusKube** 2021-06-04 16:17 UTC
Labels: bug
